application: mydeskview
version: 4
runtime: python
api_version : 1
handlers:
- url : /css
  static_dir : css
- url : /data
  static_dir : data
- url : /img
  static_dir : img
- url : /js
  static_dir : js
- url : /*
  script : main.py
builtins:
- remote_api: on

